### ISSUE TITLE
Can't get things working.

### ISSUE THREAD

**Issue by rafaleo** [TheApeMachine/keyword-extraction#2]
At this line `output_evaluation(inp)` I get error: 
```
inp = "Little gray mouse fears big brown cat."
output_evaluation(inp)
```
inp = "Little gray mouse fears big brown cat."

output_evaluation(inp)
Traceback (most recent call last):

  File "<ipython-input-19-d76ac325b52c>", line 1, in <module>
    output_evaluation(inp)

  File "<ipython-input-2-9436e4c8778c>", line 330, in output_evaluation
    encoder1, attn_decoder1, input_sentence

  File "<ipython-input-2-9436e4c8778c>", line 290, in evaluate
    input_variable  = variable_from_sentence(input_lang, sentence)

  File "<ipython-input-2-9436e4c8778c>", line 170, in variable_from_sentence
    indexes = indexes_from_sentence(lang, sentence)

  File "<ipython-input-2-9436e4c8778c>", line 166, in indexes_from_sentence
    return [lang.word2index[word] for word in sentence.split(' ')]

  File "<ipython-input-2-9436e4c8778c>", line 166, in <listcomp>
    return [lang.word2index[word] for word in sentence.split(' ')]

KeyError: 'Little'

This looks like some compability issue maybe. It's not said the `torch` library can be installed as `PyTorch` - in my case I'm unable to install anything else so use `Pytorch`. 

Not sure it's the case.

**Comment by rafaleo** [comment]
Found that in the code is many unhandled exceptions. In this situation in:
```
def indexes_from_sentence(lang, sentence):  #lang=input_lang; sentence=pair[0]    
    sent_spl = sentence.split(' ')
    return [lang.word2index[word] for word in sent_spl **if word in lang.word2index**]
```
If word is not in the `lang.word2index` it throws an error. This condition works but don't know whether it's properly set and won't cause errors further on.

Anyway, I have many other errors like:

> IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number
at line `encoder_output, encoder_hidden = encoder(input_variable[ei], encoder_hidden)` of `evaluate` functions and many others.

**Comment by TheApeMachine** [comment]
Is it because you are using a period at the end of your sentence? I have never tested that condition, so you can try removing the period and see if that resolves the issue. All punctuation/special characters need to be removed I think.
